
export const CURRENCIES = {
    USD: { code: 'USD', symbol: '$', rate: 1, name: 'US Dollar' },
    AED: { code: 'AED', symbol: 'AED', rate: 3.67, name: 'United Arab Emirates Dirham' },
    SAR: { code: 'SAR', symbol: 'SAR', rate: 3.75, name: 'Saudi Riyal' },
    KWD: { code: 'KWD', symbol: 'KWD', rate: 0.31, name: 'Kuwaiti Dinar' },
    QAR: { code: 'QAR', symbol: 'QAR', rate: 3.64, name: 'Qatari Riyal' },
    BHD: { code: 'BHD', symbol: 'BHD', rate: 0.38, name: 'Bahraini Dinar' },
    OMR: { code: 'OMR', symbol: 'OMR', rate: 0.38, name: 'Omani Rial' },
    EGP: { code: 'EGP', symbol: 'EGP', rate: 48.50, name: 'Egyptian Pound' },
    EUR: { code: 'EUR', symbol: '€', rate: 0.92, name: 'Euro' },
    GBP: { code: 'GBP', symbol: '£', rate: 0.79, name: 'British Pound' },
    JOD: { code: 'JOD', symbol: 'JOD', rate: 0.79, name: 'Jordanian Dinar' },
    JPY: { code: 'JPY', symbol: '¥', rate: 0.79, name: 'Japanese Yen' },
    CNY: { code: 'CNY', symbol: '¥', rate: 0.79, name: 'Chinese Yuan' },
    UKP: { code: 'UKP', symbol: '£', rate: 0.79, name: 'British Pound' },
    AUD: { code: 'AUD', symbol: '$', rate: 0.79, name: 'Australian Dollar' },
    CAD: { code: 'CAD', symbol: '$', rate: 0.79, name: 'Canadian Dollar' },
    CHF: { code: 'CHF', symbol: 'CHF', rate: 0.79, name: 'Swiss Franc' },
    DKK: { code: 'DKK', symbol: 'DKK', rate: 0.79, name: 'Danish Krone' },
    HKD: { code: 'HKD', symbol: 'HKD', rate: 0.79, name: 'Hong Kong Dollar' },
    NZD: { code: 'NZD', symbol: '$', rate: 0.79, name: 'New Zealand Dollar' },
    SEK: { code: 'SEK', symbol: 'SEK', rate: 0.79, name: 'Swedish Krona' },
    ZAR: { code: 'ZAR', symbol: 'ZAR', rate: 0.79, name: 'South African Rand' },
    INR: { code: 'INR', symbol: '₹', rate: 0.79, name: 'Indian Rupee' },
    MYR: { code: 'MYR', symbol: 'RM', rate: 0.79, name: 'Malaysian Ringgit' },
    PHP: { code: 'PHP', symbol: '₱', rate: 0.79, name: 'Philippine Peso' },
    THB: { code: 'THB', symbol: '฿', rate: 0.79, name: 'Thai Baht' },
    VND: { code: 'VND', symbol: '₫', rate: 0.79, name: 'Vietnamese Dong' },
    TUR: { code: 'TUR', symbol: '₺', rate: 0.79, name: 'Turkish Lira' },
} as const;

export type CurrencyCode = keyof typeof CURRENCIES;

export const COUNTRY_TO_CURRENCY: Record<string, CurrencyCode> = {
    US: 'USD',
    AE: 'AED',
    SA: 'SAR',
    KW: 'KWD',
    QA: 'QAR',
    BH: 'BHD',
    OM: 'OMR',
    EG: 'EGP',
    GB: 'GBP',
    DE: 'EUR',
    FR: 'EUR',
    IT: 'EUR',
    ES: 'EUR',
    NL: 'EUR',
    JO: 'JOD',
    TR: 'TUR',
    IN: 'INR',
    MY: 'MYR',
    PH: 'PHP',
    TH: 'THB',
    VN: 'VND',
    UK: 'UKP',
    AU: 'AUD',
    CA: 'CAD',
    CH: 'CHF',
    DK: 'DKK',
    HK: 'HKD',
    NZ: 'NZD',
    SE: 'SEK',
    ZA: 'ZAR',
    // Add more mappings as needed
};

export const DEFAULT_CURRENCY: CurrencyCode = 'USD';
